#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
PROFILES = {
    "v1": (
        ROOT / "contracts" / "davinci-agent-v1.json",
        ROOT / "web" / "shared" / "generated" / "davinci-contracts.js",
    ),
    "v2": (
        ROOT / "contracts" / "davinci-agent-v2.json",
        ROOT / "web" / "shared" / "generated" / "davinci-contracts-v2.js",
    ),
}


def _load_contract(path: Path) -> dict[str, object]:
    sys.path.insert(0, str(ROOT))
    from app.agui.contracts import load_contract_registry

    registry = load_contract_registry(path)
    return registry.raw_contract


def _javascript(payload: dict[str, object], digest: str) -> str:
    tools = payload["tools"]
    assert isinstance(tools, list)
    templates = payload["schemaTemplates"]
    assert isinstance(templates, dict)

    def enrich(tool: dict[str, object]) -> dict[str, object]:
        return {
            **tool,
            "inputSchema": templates[tool["inputTemplate"]],
            "outputSchema": templates[tool["outputTemplate"]],
        }

    public_tools = [
        enrich(tool) for tool in tools if tool.get("public") is True
    ]
    internal_tools = [
        enrich(tool) for tool in tools if tool.get("public") is not True
    ]
    errors = payload["errors"]

    def encode(value: object) -> str:
        return json.dumps(
            value,
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        )

    lines = [
            "// Generated by scripts/generate-davinci-contracts.py. Do not edit.",
            f"export const CONTRACT_VERSION = '{payload['contractVersion']}'",
            f"export const PROTOCOL_VERSION = '{payload['protocolVersion']}'",
            f"export const CONTRACT_DIGEST = '{digest}'",
            f"export const PUBLIC_TOOL_CONTRACTS = Object.freeze({encode(public_tools)})",
            f"export const INTERNAL_TOOL_CONTRACTS = Object.freeze({encode(internal_tools)})",
            f"export const ERROR_SCHEMAS = Object.freeze({encode(errors)})",
    ]
    if "pageStateSchema" in payload:
        lines.append(
            f"export const PAGE_STATE_SCHEMA = Object.freeze({encode(payload['pageStateSchema'])})"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--profile", choices=["all", *PROFILES], default="all")
    args = parser.parse_args()

    selected = PROFILES if args.profile == "all" else {args.profile: PROFILES[args.profile]}
    for contract_path, generated_path in selected.values():
        contract_bytes = contract_path.read_bytes()
        payload = _load_contract(contract_path)
        expected = _javascript(payload, hashlib.sha256(contract_bytes).hexdigest())

        if args.check:
            if not generated_path.exists():
                print(f"generated contract is missing: {generated_path}", file=sys.stderr)
                return 1
            if generated_path.read_text(encoding="utf-8") != expected:
                print(f"generated contract is stale: {generated_path}", file=sys.stderr)
                return 1
            continue

        generated_path.parent.mkdir(parents=True, exist_ok=True)
        generated_path.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
